### ISSUE TITLE
[tracking bug] CoreDNS Operator

### ISSUE THREAD

**Issue by johnsonj** [kubernetes-sigs/cluster-addons#47]
**Description**
CoreDNS Operator aims to manage the lifecycle of the CoreDNS installation in the cluster. It is concerned with the installation, updating, and configuration of CoreDNS.

**Project Goal**
Define the set of milestones and criteria for productionizing the CoreDNS operator. The current operator is a proof of concept of the add-on library. The goal of the alpha operator is to provide a minimal feature set that is manageable, predictable, and reliable in a production environment.

- [ ] [Issue](https://github.com/kubernetes-sigs/addon-operators/issues/36): **Implement CoreDNS operator smoke test.**
Implementing and validating various scenarios like creation, deletion, configuration change, etc.
This work will require adding multiple versions to the CoreDNS version directory.
- [ ] [Issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65): **Provide metrics in the kubebuilder-declarative-pattern library**
A user should be able to emit metrics on the Prometheus metrics endpoint. Metrics should be written to the controller-runtime Prometheus Registry.
- [x] [Issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56): **Integrate Kustomize with kubebuilder-declarative-pattern**
Finish and share design doc.
- [ ] [Issue](https://github.com/kubernetes-sigs/addon-operators/issues/27): **Implement rolling updates for ConfigMap**
Rolling update for Configs should use hashed names (kustomize supports this) Issue

**Comment by johnsonj** [comment]
Pulling in the content from @Abhik1998 's issue #40

**Comment by vanou** [comment]
Hello. I would like to work on issues listed here.
Can I work on them till GSoC 2020 starts?

**Comment by Abhik1998** [comment]
@vanou I will be working upon them.

**Comment by vanou** [comment]
@Abhik1998 I understand. Sorry for worrying.

**Comment by eloyekunle** [comment]
@Abhik1998 Projects are open to all interested GSoC participants. Only when your proposal is accepted by the organization will you be working on it.

**Comment by Abhik1998** [comment]
@eloyekunle  you are right but @vanou is not a GSoC participant.

**Comment by vanou** [comment]
Yes. I’m not GSoC participant.
Cheer up @Abhik1998 !

However, if and only if you don’t finish these issues in GSoC terms (till August 26?), I would like to work on this.

**Comment by johnsonj** [comment]
I adjusted the branding on this issue. This an open source project and our roadmap is open to all participants (GSoC or otherwise).

**Comment by vanou** [comment]
I understand. I'll do my best.

**Comment by vanou** [comment]
First, I'll tackle [Provide metrics in the kubebuilder-declarative-pattern library](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65) .

**Comment by vanou** [comment]
Now I'm working on 2nd issue, and after I finish it, I would like to tackle 1st issue([Implement CoreDNS operator smoke test](https://github.com/kubernetes-sigs/addon-operators/issues/36)).

**Comment by vanou** [comment]
(Replying to [this message](https://github.com/kubernetes-sigs/cluster-addons/issues/36#issuecomment-607755755) on #36 )
> Heyy @vanou, Care to release one issue?

Hi @SomtochiAma . Sorry for late reply.

I'm working on [Provide metrics in the kubebuilder-declarative-pattern library](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65). However my colleague @longkb working on #46 related to [Integrate Kustomize with kubebuilder-declarative-pattern](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56) left company at end of this March and I was delegated access to this PR from him.

Now there is two options for us:
 1. As you are now working on,
    * you take assignee of [kustomize integration issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56) and work on it
    * and I give up #46 (because this issue is closely related to [kustomize integration issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56))
      (or can I work on #46 after you finish [kustomize integration issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56)?)
    * and I concentrate on [Provide metrics in the kubebuilder-declarative-pattern library](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65) & [Implement CoreDNS operator smoke test](https://github.com/kubernetes-sigs/addon-operators/issues/36) (or one of it) which I currently have assignee.
 1. Another way is
    * I un-assign me from [Provide metrics in the kubebuilder-declarative-pattern library](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65) & [Implement CoreDNS operator smoke test](https://github.com/kubernetes-sigs/addon-operators/issues/36)
    * and you take assignee of above two
    * then l work on #46 & [kustomize integration issue](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/56)

Which one is better for you. And sorry for annoying you. If you reply to this, it is thankful for me.

**Comment by vanou** [comment]
Any way, currently I’m working on [Provide metrics in the kubebuilder-declarative-pattern library](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/issues/65), I unassign me from #36.

Sorry.

**Comment by SomtochiAma** [comment]
@vanou Thank you for being considerate! I will pick up #36. Although, I will wait for the #50 to be merged before starting as it introduces significant file changes

**Comment by vanou** [comment]
@SomtochiAma OK. And sorry for I haven't unassigned me from #36 , now I have.
Thank you.

**Comment by atoato88** [comment]
What's the current status of this, does anyone know that?
Is it OK to close this issue?

Some issues related to this topic are described in top of this PR.
- #36 : closed by fejta-bot, current status is unknown..
- kubernetes-sigs/kubebuilder-declarative-pattern/issues/65 : closed
- kubernetes-sigs/kubebuilder-declarative-pattern/issues/56 : closed by fejta-bot, but some PRs related to this are merged.
- #27 : closed

Mainly, related PRs are merged, but I'm not sure whether can I close or not.
